[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  https://github.com/pschatzmann/ESP32-A2DP.git#v1.8.9
board_build.partitions = huge_app.csv
build_flags =
  -DCORE_DEBUG_LEVEL=3
