"""
Convert an audio file (MP3/WAV/FLAC/OGG) or generate a test signal
to src/test_audio.h for embedding in ESP32 firmware as PCM samples.

Usage:
  python tools/make_test_audio.py <input.mp3|wav|flac> [max_seconds]
      Convert an audio file.  max_seconds defaults to 15.

  python tools/make_test_audio.py --generate
      Generate a built-in C-major chord test signal (~3 s).

Output:  src/test_audio.h  — #include this in main.cpp
Requires: pip install miniaudio
"""

import sys, os, struct, math, wave

TARGET_RATE = 44100
OUT_PATH    = os.path.join(os.path.dirname(__file__), "..", "src", "test_audio.h")


# ------------------------------------------------------------------ helpers --

def resample(samples: list, src_rate: int, dst_rate: int) -> list:
    """Linear-interpolation resampling."""
    if src_rate == dst_rate:
        return samples
    ratio  = src_rate / dst_rate
    length = int(len(samples) / ratio)
    out    = []
    for i in range(length):
        p   = i * ratio
        lo  = int(p)
        hi  = min(lo + 1, len(samples) - 1)
        out.append(int(samples[lo] + (samples[hi] - samples[lo]) * (p - lo)))
    return out


def write_header(samples: list, source_desc: str):
    duration = len(samples) / TARGET_RATE
    size_kb  = len(samples) * 2 / 1024

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write(f"// Auto-generated by make_test_audio.py\n")
        f.write(f"// Source : {source_desc}\n")
        f.write(f"// Content: {duration:.2f}s  {len(samples)} samples  {size_kb:.0f} KB\n")
        f.write(f"// Rate   : {TARGET_RATE} Hz  mono  int16_t  (loops in firmware)\n")
        f.write(f"#pragma once\n")
        f.write(f"static const int32_t kTestAudioLen = {len(samples)};\n")
        f.write(f"static const int16_t kTestAudio[{len(samples)}] = {{\n")

        cols = 12
        for i in range(0, len(samples), cols):
            row = samples[i : i + cols]
            f.write("  " + ", ".join(f"{v:6d}" for v in row) + ",\n")

        f.write("};\n")

    print(f"[make_test_audio] Written: {os.path.normpath(OUT_PATH)}")
    print(f"[make_test_audio] {duration:.2f}s  |  {len(samples):,} samples  |  {size_kb:.0f} KB in flash")


# --------------------------------------------------- MP3 / WAV / any format --

def from_audio(path: str, max_sec: float = 15.0):
    try:
        import miniaudio
    except ImportError:
        sys.exit("miniaudio not found — run:  pip install miniaudio")

    print(f"[make_test_audio] Decoding {os.path.basename(path)} …")
    decoded = miniaudio.decode_file(
        path,
        output_format=miniaudio.SampleFormat.SIGNED16,
        nchannels=1,
        sample_rate=TARGET_RATE,
    )
    # decoded.samples is an array.array of int16
    all_samples = list(decoded.samples)

    max_frames = int(max_sec * TARGET_RATE)
    if len(all_samples) > max_frames:
        all_samples = all_samples[:max_frames]
        print(f"[make_test_audio] Trimmed to {max_sec:.0f}s")

    write_header(all_samples, os.path.basename(path))


# --------------------------------------------------------------- generate mode --

def generate():
    """
    Generate a 3-second C-major chord with harmonics.
    Sounds like a piano chord — rich enough to reveal BT codec quality,
    distortion, frequency-response issues.
    """
    duration = 3.0
    n        = int(TARGET_RATE * duration)
    PEAK     = 28000   # leave headroom below int16 max (32767)

    # C-major: C4 261.63, E4 329.63, G4 392.00 Hz
    # Each with harmonics (fundamental + 2nd + 3rd) for piano-like timbre
    freqs = [
        (261.63, 1.00),
        (523.25, 0.50),
        (784.88, 0.25),
        (329.63, 0.85),
        (659.25, 0.40),
        (988.88, 0.20),
        (392.00, 0.70),
        (784.00, 0.35),
        (1176.0, 0.17),
    ]
    total_weight = sum(w for _, w in freqs)

    def envelope(i):
        """Simple attack + decay envelope — makes it sound more natural."""
        t = i / TARGET_RATE
        attack  = min(t / 0.01, 1.0)           # 10 ms attack
        decay   = math.exp(-t * 0.8)            # slow exponential decay
        return attack * decay

    samples = []
    for i in range(n):
        v = 0.0
        for freq, weight in freqs:
            v += weight * math.sin(2.0 * math.pi * freq * i / TARGET_RATE)
        v   = (v / total_weight) * envelope(i) * PEAK
        samples.append(max(-32768, min(32767, int(v))))

    write_header(samples, "generated C-major chord (261/329/392 Hz + harmonics)")


# ----------------------------------------------------------------------- main --

def main():
    if len(sys.argv) < 2 or sys.argv[1] == "--generate":
        print("[make_test_audio] Generating built-in test signal …")
        generate()
    else:
        path    = sys.argv[1]
        max_sec = float(sys.argv[2]) if len(sys.argv) > 2 else 15.0
        from_audio(path, max_sec)

    print("[make_test_audio] Done.  Rebuild and upload firmware.")


if __name__ == "__main__":
    main()
